analyze_mode: false
betas: !!python/tuple
- 0.9
- 0.999
class_weights: !!python/object/apply:torch._utils._rebuild_tensor_v2
- !!python/object/apply:torch.storage._load_from_bytes
  - !!binary |
    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
    Z2UKcQFYDQAAADI0ODY0MzEyOTc1MzZxAlgDAAAAY3B1cQNLCk50cQRRLoACXXEAWA0AAAAyNDg2
    NDMxMjk3NTM2cQFhLgoAAAAAAAAA5KLvPkwzsz8BhLw/Pnb0P6PclT/sV8Q/t0uAPw2nAD8OZ7A+
    RuFHPg==
- 0
- !!python/tuple
  - 10
- !!python/tuple
  - 1
- false
- !!python/object/apply:collections.OrderedDict
  - []
cohsep_ratio: 0.2
dist_eps: 1.0e-08
hidden_shape: 768
label_smoothing: 0.1
lambda0: 0.1
lambda1: 0.25
lambda2: 0.25
lr: 0.0001
max_seq_length: 100
num_classes: 10
num_prototypes: 500
optim_eps: 1.0e-08
proto_training_weights: true
